openapi: 3.0.0
info:
  title: Customer Orders API
  version: '1.0'
  description: API for managing customer orders
servers:
  - url: https://api.example.com/v1
paths:
  /orders:
    get:
      summary: List all orders
      description: Retrieve a list of customer orders
      operationId: listOrders
      responses:
        '200':
          description: Successfully retrieved orders
          content:
            application/json:
              schema:
                type: object
                properties:
                  orders:
                    type: array
                    items:
                      $ref: '#/components/schemas/Order'
              examples:
                success:
                  value:
                    orders: [
                      {
                        order_id: "ORD-001",
                        customer_name: "John Smith",
                        quantity: 3,
                        order_date: "2023-11-22T10:30:00Z",
                        status: {
                          is_pending: false,
                          is_processing: false,
                          is_shipped: false,
                          is_delivered: true
                        },
                        ship_to: "123 Main St, Denver CO 80202",
                        total_amount: 149.99
                      },
                      {
                        order_id: "ORD-002",
                        customer_name: "Jane Doe",
                        quantity: 1,
                        order_date: "2023-11-21T15:45:00Z",
                        status: {
                          is_pending: false,
                          is_processing: true,
                          is_shipped: false,
                          is_delivered: false
                        },
                        ship_to: "456 Oak Ave, Seattle WA 98101",
                        total_amount: 49.99
                      }
                    ]
                  }
  /orders/{order_id}:
    get:
      summary: Get order by ID
      parameters:
        - name: order_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Order found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
              examples:
                success:
                  value:
                    order_id: "ORD-001"
                    customer_name: "John Smith"
                    quantity: 3
                    order_date: "2023-11-22T10:30:00Z"
                    status: {
                      is_pending: false,
                      is_processing: false,
                      is_shipped: false,
                      is_delivered: true
                    }
                    ship_to: "123 Main St, Denver CO 80202"
                    total_amount: 149.99
components:
  schemas:
    Order:
      type: object
      properties:
        order_id:
          type: string
        customer_name:
          type: string
        quantity:
          type: integer
        order_date:
          type: string
          format: date-time
        status:
          type: object
          properties:
            is_pending:
              type: boolean
            is_processing:
              type: boolean
            is_shipped:
              type: boolean
            is_delivered:
              type: boolean
        ship_to:
          type: string
        total_amount:
          type: number