openapi: 3.0.0
info:
  title: Customer Orders API
  version: '1.0'
paths:
  /orders:
    get:
      summary: List all orders
      responses:
        '200':
          description: List of orders
          content:
            application/json:
              example:
                orders:
                  - order_id: "ORD-001"
                    customer_name: "John Smith"
                    quantity: 3
                    order_date: "2023-11-22T10:30:00Z"
                    status:
                      is_pending: false
                      is_processing: false
                      is_shipped: false
                      is_delivered: true
                    ship_to: "123 Main St, Denver CO 80202"
                    total_amount: 149.99
                  - order_id: "ORD-002"
                    customer_name: "Jane Doe"
                    quantity: 1
                    order_date: "2023-11-21T15:45:00Z"
                    status:
                      is_pending: false
                      is_processing: true
                      is_shipped: false
                      is_delivered: false
                    ship_to: "456 Oak Ave, Seattle WA 98101"
                    total_amount: 49.99
                  - order_id: "ORD-003"
                    customer_name: "Bob Wilson"
                    quantity: 2
                    order_date: "2023-11-22T09:15:00Z"
                    status:
                      is_pending: true
                      is_processing: false
                      is_shipped: false
                      is_delivered: false
                    ship_to: "789 Pine St, Austin TX 78701"
                    total_amount: 99.99
  /orders/{order_id}:
    get:
      summary: Get order by ID
      parameters:
        - name: order_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Single order
          content:
            application/json:
              example:
                order_id: "ORD-001"
                customer_name: "John Smith"
                quantity: 3
                order_date: "2023-11-22T10:30:00Z"
                status:
                  is_pending: false
                  is_processing: false
                  is_shipped: false
                  is_delivered: true
                ship_to: "123 Main St, Denver CO 80202"
                total_amount: 149.99